import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col bg-gradient-to-r from-slate-950 to-slate-900 text-white ">
          <header>
            <ul
              className="flex justify-around items-center md:justify-center md:gap-4 font-extrabold md:text-xl cursor-pointer my-10
         "
            >
              <Link href={"/"}>
                <li className="hover:text-rose-700  duration-700">Home</li>
              </Link>
              <Link href={"/About"}>
                <li className="hover:text-rose-700 duration-700">About</li>
              </Link>
              <Link href={"/Skills"}>
                <li className="hover:text-rose-700 duration-700">Skills</li>
              </Link>
              <Link href={"/Projects"}>
                <li className="hover:text-rose-700 duration-700">Projects</li>
              </Link>
              <Link href={"/Blogs"}>
                <li className="hover:text-rose-700 duration-700">Blogs</li>
              </Link>
              <Link href={"/Contact"}>
                <li className="hover:text-rose-700 duration-700">Contact us</li>
              </Link>
            </ul>
          </header>
          <main className="flex-grow">{children}</main>
          <footer>This is the Footer</footer>
        </div>
      </body>
    </html>
  );
}
