import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="text-center text-rose-600 font-extrabold text-3xl  ">
          Navigation with Next.Js
        </h1>

        <div className="flex justify-around font-bold my-8 bg-slate-600 mx-20 py-1 ">
          <Link href={"/"}>Home</Link>
          <Link href={"/About"}>About</Link>
        </div>

        {children}
      </body>
    </html>
  );
}
